// Compile-time DEFAULTS only.
//
// All user-facing settings below are persisted in NVS by the webflasher and
// loaded at boot via Config::begin(). The values here are fallbacks used only
// when NVS has not yet been provisioned. To configure a device, run the
// webflasher page (docs/flasher/index.html) — do not edit this file.

#define WIFI_SSID      "-your-router-name-"
#define WIFI_PASSWORD  "-your-router-password-"

#define TIMEZONE_NAME  "usCT"  // resolved via timezoneByName() in NTP_Time.h

const int UPDATE_INTERVAL_SECS = 30UL * 60UL;  // 30 minutes

// Screen off hours — backlight cuts at NIGHT_OFF_HOUR:59, comes back at NIGHT_ON_HOUR:00
#define NIGHT_OFF_HOUR  23
#define NIGHT_ON_HOUR    6

// Fixed screen brightness 0–255. Webflasher overrides this via NVS.
#define SCREEN_BRIGHTNESS 150

// Number of carousel pages for the bottom two sections
#define PAGE_COUNT 2

// For units use "metric" or "imperial"
const String units = "metric";

// OpenWeatherMap defaults — overridden by the webflasher.
// Sign up at https://openweathermap.org/ to get a free key.
const String api_key = "-your-openweathermap.org api key-";

// New York, Empire State Building
const String latitude  = "40.749778527083656";  // -90 to 90 (negative for Southern hemisphere)
const String longitude = "-73.98629815117553";  // -180 to 180 (negative for West)

// For language codes see https://openweathermap.org/current#multi
const String language = "en";

// Short day of week abbreviations used in 4 day forecast (change to your language)
const String shortDOW[8] = { "???", "SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT" };

// Localisation — not user-tunable via webflasher.
const char sunStr[] = "Sun";
const char cloudStr[] = "Cloud";
const char humidityStr[] = "Humidity";
const String moonPhase[8] = { "New", "Waxing", "1st qtr", "Waxing", "Full", "Waning", "Last qtr", "Waning" };
